name: Debug
on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python
