

name: Debug
on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-24.04
    container:
      image: python:3.10-slim
    steps:
     - name: Install GLIBC
       run: |
          apt-get update
          apt-get install -y libc6
     - uses: actions/setup-python@v5
       with:
          python-version: "3.10"
     - run: python
