name: Test Different Docker Images Alternate

on:
  workflow_dispatch:
  push:

jobs:
  test_python_3_10_debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python and GLIBC
        run: |
          apt-get update
          apt-get install -y python3.10 python3.10-venv python3.10-dev libc6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check Python version
        run: python3.10 --version

      - name: Run a simple Python script
        run: |
          echo 'print("Hello, World!")' > hello.py
          python3.10 hello.py
